# Generated by Django 5.2.6 on 2025-09-14 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='posts/', verbose_name='Post Image')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes Count')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Comments Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Gender')),
                ('profession', models.CharField(blank=True, max_length=60, verbose_name='Profession')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Avatar')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profiles/', verbose_name='Profile Picture')),
                ('profile_cover', models.ImageField(blank=True, upload_to='profiles/cover/', verbose_name='Profile Cover')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
