# Generated by Django 5.2.6 on 2025-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
